import matplotlib.pyplot as plt
import numpy as np
import cv2
import tensorflow as tf
from tensorflow import keras

class_names=['air hockey',
 'ampute football',
 'archery',
 'arm wrestling',
 'axe throwing',
 'balance beam',
 'barell racing',
 'baseball',
 'basketball',
 'baton twirling',
 'bike polo',
 'billiards',
 'bmx',
 'bobsled',
 'bowling',
 'boxing',
 'bull riding',
 'bungee jumping',
 'canoe slamon',
 'cheerleading',
 'chuckwagon racing',
 'cricket',
 'croquet',
 'curling',
 'disc golf',
 'fencing',
 'field hockey',
 'figure skating men',
 'figure skating pairs',
 'figure skating women',
 'fly fishing',
 'football',
 'formula 1 racing',
 'frisbee',
 'gaga',
 'giant slalom',
 'golf',
 'hammer throw',
 'hang gliding',
 'harness racing',
 'high jump',
 'hockey',
 'horse jumping',
 'horse racing',
 'horseshoe pitching',
 'hurdles',
 'hydroplane racing',
 'ice climbing',
 'ice yachting',
 'jai alai',
 'javelin',
 'jousting',
 'judo',
 'lacrosse',
 'log rolling',
 'luge',
 'motorcycle racing',
 'mushing',
 'nascar racing',
 'olympic wrestling',
 'parallel bar',
 'pole climbing',
 'pole dancing',
 'pole vault',
 'polo',
 'pommel horse',
 'rings',
 'rock climbing',
 'roller derby',
 'rollerblade racing',
 'rowing',
 'rugby',
 'sailboat racing',
 'shot put',
 'shuffleboard',
 'sidecar racing',
 'ski jumping',
 'sky surfing',
 'skydiving',
 'snow boarding',
 'snowmobile racing',
 'speed skating',
 'steer wrestling',
 'sumo wrestling',
 'surfing',
 'swimming',
 'table tennis',
 'tennis',
 'track bicycle',
 'trapeze',
 'tug of war',
 'ultimate',
 'uneven bars',
 'volleyball',
 'water cycling',
 'water polo',
 'weightlifting',
 'wheelchair basketball',
 'wheelchair racing',
 'wingsuit flying']
class_names=[i.title() for i in class_names]

MODEL=keras.models.load_model('sportclass_model.h5')
def predictor(image_name):
    img_data=cv2.imread(image_name)
    resize_image=cv2.resize(img_data, (224,224))
    img_data=resize_image/255.0
    img_data=np.expand_dims(img_data, axis=0)
    pred=MODEL.predict(img_data)
    predicted_sport=class_names[np.argmax(pred[0])]
    return predicted_sport
    
print(predictor('rugby.jpeg'))

